language: php
php:
  - 8.0
  - 8.1
  

install:
  - COMPOSER_MEMORY_LIMIT=-1 travis_retry composer install
  - pear install PHP_CodeSniffer
  - phpenv rehash

script:
  - phpcs --standard=PSR2 $(find src/ -name '*.php')